# fly.toml file generated for odin-blog on 2023-04-13T20:28:37-04:00

app = "odin-blog"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "sjc"
processes = []

[[services]]
  internal_port = 3000
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
